# Generated by Django 5.1.4 on 2025-05-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0003_userbudget_alter_groupmember_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budzetApp.budget')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budzetApp.transaction')),
            ],
        ),
    ]
