# Generated by Django 4.2.20 on 2025-05-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0004_budgettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budzety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budzetApp.budzety')),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transakcje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budzetApp.kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budzetApp.uzytkownicy')),
            ],
        ),
        migrations.CreateModel(
            name='UzytkownikBudzetPolaczenia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budzetApp.budzety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budzetApp.uzytkownicy')),
            ],
            options={
                'unique_together': {('user', 'budget')},
            },
        ),
    ]
