# Generated by Django 5.1.4 on 2025-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0004_budgettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default='My Budget', max_length=100),
        ),
    ]
