# Generated by Django 4.2.20 on 2025-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0005_budzety_kategorie_uzytkownicy_transakcje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budzety',
            name='uzytkownicy',
            field=models.ManyToManyField(related_name='budzety', through='budzetApp.UzytkownikBudzetPolaczenia', to='budzetApp.uzytkownicy'),
        ),
    ]
