# Generated by Django 5.1.4 on 2025-05-14 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0005_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
