# Generated by Django 4.2.20 on 2025-05-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0006_budzety_uzytkownicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorie',
            name='type',
        ),
    ]
