# Generated by Django 4.2.20 on 2025-05-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0007_remove_kategorie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transakcje',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budzetApp.budzety'),
        ),
    ]
