# Generated by Django 5.1.4 on 2025-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0007_remove_budget_category_category_budgetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbudget',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
