# Generated by Django 5.1.4 on 2025-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0008_alter_userbudget_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbudget',
            unique_together=set(),
        ),
    ]
