# Generated by Django 4.2.20 on 2025-05-14 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0008_transakcje_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budzety',
            old_name='uzytkownicy',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='budzety',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
