# Generated by Django 4.2.20 on 2025-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0009_rename_uzytkownicy_budzety_users_alter_budzety_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
