# Generated by Django 4.2.20 on 2025-06-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0012_budgetinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgettransaction',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgettransaction',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userbudget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbudget',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='userbudget',
            name='user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetTransaction',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserBudget',
        ),
    ]
