# Generated by Django 4.2.20 on 2025-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0013_remove_budgettransaction_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownicy',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
