# Generated by Django 4.2.20 on 2025-06-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzetApp', '0014_alter_uzytkownicy_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetinvitation',
            name='invited_user',
        ),
    ]
